AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Spin up cluster of instances for keras tuning
Parameters:
  ModelPath:
    Type: String
    Description: s3 path to place output
    Default: s3://sagemaker-scf/default
Resources:
  EvalSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Security Group for Model Eval
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6010
          ToPort: 6012
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
  EvalRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ec2.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: eval-model-policy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: [
              's3:*',
              'iam:PassRole',
              ]
            Resource: '*'
  EvalRoleInstProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref EvalRole
  EvalLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t3.micro
        ImageId: ami-0e2a8509db267f072
        KeyName: amKeyPair
        SecurityGroups:
          - !Ref EvalSecurityGroup
      LaunchTemplateName: !Sub ${AWS::StackName}_eval
  EvalInstance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref EvalLaunchTemplate
        Version: '1'
      IamInstanceProfile: !Ref EvalRoleInstProfile
      Tags:
        -
          Key: Name
          Value: !Sub ${AWS::StackName}_eval
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash
              yum -y install git
              cd /home/ec2-user
              su ec2-user -c 'git clone https://github.com/scfox/keras_tuner_aws.git'
              su ec2-user -c 'cd ~/keras_tuner_aws; ./start_tensorboard.sh ${ModelPath};'
              su ec2-user -c 'cd ~/keras_tuner_aws; ./start_jupyter.sh;'
            - ModelPath: !Ref ModelPath
Outputs:
  Tensorboard:
    Value: !Join ['', ['http://', !GetAtt EvalInstance.PublicIp, ':6012' ]]
  Jupyter:
    Value: !Join ['', ['http://', !GetAtt EvalInstance.PublicIp, ':6010' ]]
