AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Spin up cluster of instances for keras tuning
Parameters:
  NumSlaves:
    Type: Number
    Description: Number of Slaves to run
    Default: 2
  SlavesInstType:
    Type: String
    Description: Slave instance type
    Default: t3.small
  OutputPath:
    Type: String
    Description: s3 path to place output
    Default: s3://sagemaker-scf/catchjoe
  MaxTrials:
    Type: String
    Description: max trials to run
    Default: 25
  MaxEpochs:
    Type: String
    Description: max epochs per trial
    Default: 3
Resources:
  TunerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Security Group for Keras Tuning
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6012
          ToPort: 6012
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
  TunerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ec2.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: keras-tuner-policy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: [
              's3:*',
              'iam:PassRole',
              ]
            Resource: '*'
  TunerRoleInstProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref TunerRole
  MasterLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t3.micro
        ImageId: ami-0e2a8509db267f072
        KeyName: amKeyPair
        SecurityGroups:
          - !Ref 'TunerSecurityGroup'
      LaunchTemplateName: !Sub ${AWS::StackName}_tuner_master
  TunerMaster:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref MasterLaunchTemplate
        Version: '1'
      IamInstanceProfile: !Ref TunerRoleInstProfile
      Tags:
        -
          Key: Name
          Value: Tuner_master
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum -y install git
          cd /home/ec2-user
          su ec2-user -c 'git clone https://github.com/scfox/keras_tuner_aws.git'
          su ec2-user -c 'source /home/ec2-user/anaconda3/bin/activate tensorflow2_p36; cd keras_tuner_aws; pip install -r src/requirements.txt; ./start_tensorboard.sh; ./tune_master.sh;'
  SlaveLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: !Ref SlavesInstType
        ImageId: ami-0e2a8509db267f072
        KeyName: amKeyPair
        SecurityGroupIds:
          - !GetAtt TunerSecurityGroup.GroupId
        IamInstanceProfile:
          Arn: !GetAtt TunerRoleInstProfile.Arn
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: Tuner_slave
        UserData:
          Fn::Base64:
            Fn::Sub:
              - |
                #!/bin/bash
                yum -y install git
                cd /home/ec2-user
                echo ${MasterIP} > masterip.txt
                su ec2-user -c 'git clone https://github.com/scfox/keras_tuner_aws.git'
                su ec2-user -c 'cd keras_tuner_aws; ./tune_slave.sh ${MasterIP} ${OutputPath} ${MaxTrials} ${MaxEpochs};'
              - MasterIP: !GetAtt 'TunerMaster.PrivateIp'
                OutputPath: !Ref OutputPath
                MaxTrials: !Ref MaxTrials
                MaxEpochs: !Ref MaxEpochs
      LaunchTemplateName: !Sub ${AWS::StackName}_tuner_slave
  TunerSlave:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        IamFleetRole: arn:aws:iam::170290590187:role/aws-ec2-spot-fleet-tagging-role
        LaunchTemplateConfigs:
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref SlaveLaunchTemplate
              Version: '1'
        TargetCapacity: !Ref NumSlaves
Outputs:
  URL:
    Value: !Join ['', ['http://', !GetAtt TunerMaster.PublicIp, ':6012' ]]
